import React from 'react';

class Table extends React.Component{
	constructor(props){
		super(props)
	}
	render(){
		return(
			<div className="schedule-container">
				<table className="timeline-table">
					<tr>
						<td>8:00</td>
					</tr>
					<tr>
						<td>9:00</td>
					</tr>
					<tr>
						<td>10:00</td>
					</tr>
					<tr>
						<td>11:00</td>
					</tr>
					<tr>
						<td>12:00</td>
					</tr>
					<tr>
						<td>12:00</td>
					</tr>
					<tr>
						<td>12:00</td>
					</tr>
					<tr>
						<td>12:00</td>
					</tr>
					<tr>
						<td>12:00</td>
					</tr>
					<tr>
						<td>12:00</td>
					</tr>
				</table>
	
				<table className="main-table">
					<tr>
						<th>Monday</th>
						<th>Tuesday</th>
						<th>Wednesday</th>
						<th>Thursday</th>
						<th>Friday</th>
					</tr>
					<tr>
						<td>Empty</td>
						<td>Empty</td>
						<td>Empty</td>
						<td>Empty</td>
						<td>Empty</td>
					</tr>
					<tr>
						<td>Empty</td>
						<td>Empty</td>
						<td>Empty</td>
						<td>Empty</td>
						<td>Empty</td>
					</tr>
					<tr>
						<td>Empty</td>
						<td>Empty</td>
						<td>Empty</td>
						<td>Empty</td>
						<td>Empty</td>
					</tr>
					<tr>
						<td>Empty</td>
						<td>Empty</td>
						<td>Empty</td>
						<td>Empty</td>
						<td>Empty</td>
					</tr>
					<tr>
						<td>Empty</td>
						<td>Empty</td>
						<td>Empty</td>
						<td>Empty</td>
						<td>Empty</td>
					</tr>
					<tr>
						<td>Empty</td>
						<td>Empty</td>
						<td>Empty</td>
						<td>Empty</td>
						<td>Empty</td>
					</tr>
					<tr>
						<td>Empty</td>
						<td>Empty</td>
						<td>Empty</td>
						<td>Empty</td>
						<td>Empty</td>
					</tr>
					<tr>
						<td>Empty</td>
						<td>Empty</td>
						<td>Empty</td>
						<td>Empty</td>
						<td>Empty</td>
					</tr>
					<tr>
						<td>Empty</td>
						<td>Empty</td>
						<td>Empty</td>
						<td>Empty</td>
						<td>Empty</td>
					</tr>
				</table>
		</div>
		);
	}
}

export default Table;
